services:
    YZubizarreta\QuadernoReportsBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'
    YZubizarreta\QuadernoReportsBundle\Adapter\Quaderno:
        arguments:
            $config: '%yz_quaderno_reports.config%'
        public: true
