services:
    YZubizarreta\QuadernoReportsBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Tests}'
    YZubizarreta\QuadernoReportsBundle\Adapter\Quaderno:
        arguments:
            $configuration: '%yz_quaderno_reports.config%'
        public: true
    YZubizarreta\QuadernoReportsBundle\Command\RetrieveProductsCommand:
        arguments:
            $api_reports: YZubizarreta\QuadernoReportsBundle\Adapter\Quaderno
            $configuration: '%yz_quaderno_reports.config%'
            $mailer: Swift_Mailer
        public: true
